[package]
name = "geotime"
version = "0.0.1"
authors = ["Eric Walker <eric.walker@gmail.com>"]
edition = "2021"

[dependencies]
base64 = "0"
chrono = "0"
data-encoding = "2"
data-encoding-macro = "0"
hex = "0"
quick-error = "2"
serde = { version = "1" }
serde_test = "1"
